
### user registration
POST https://localhost:1337/api/auth/registration
content-type: application/json

{
    "name": "sample",
    "email": "subhadipsjsc@gmail.com",
    "password": "123456789"
}


### login
POST https://localhost:1337/api/auth/login
content-type: application/json

{
    "email": "subhadipsjsc@gmail.com",
    "password": "123456789"
}